language: node_js
node_js:
  - "lts/*"
before_script:
  - npm run lint:fix
script:
  - npm run build
deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_TOKEN
  skip_cleanup: true
  on:
    branch: 2-bundle-script
