language: node_js
node_js:
  - "lts/*"
before_script:
  - npm run lint:fix
script:
  - npm run build
before_deploy:
  - git tag -a $TRAVIS_TAG $TRAVIS_TAG -f -m $TRAVIS_TAG
  - git push origin --tags -f
  - npm version from-git
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  tag: latest
  on:
    tags: true
    branch: master
